export const CLOUDINARY_PROFILE_IMAGES_FOLDER = "PROFILE_IMAGES";
export const CLOUDINARY_MEMORY_IMAGES_FOLDER = "MEMORY_IMAGES";
export const CLOUDINARY_LICENSE_DOC_FOLDER = "LICENSE_DOCS";
export const PROCESSING_BATCH_SIZE = 100;
export const GET_REQUEST_DATA_LIMIT = 10;
export const INTERNAL_REQUEST_ALLOWED_TIME_DIFF = 5 * 60 * 1000;
export const JWT_LOGIN_SESSION_DURATION = "30d";
export const MIN_USER_AGE = 15;
export const MIN_LICENSE_PLATE_LENGTH = 3;
export const MIN_PASSWORD_LENGTH = 8;
export const MAX_PASSWORD_LENGTH = 20;
export const MIN_USERNAME_LENGTH = 3;
export const MAX_USERNAME_LENGTH = 20;
export const OTP_EXPIRY_TIME = "1 hour";
export const MAX_UNIQUE_IMAGE_NAME_GENERATION_ATTEMPTS = 10;
export const MAX_PROFILE_IMAGE_SIZE = 5 * 1024 * 1024;
export const MAX_MEMORY_IMAGE_SIZE = 10 * 1024 * 1024;
export const MAX_EXPENSE_RECEIPT_IMAGE_SIZE = 5 * 1024 * 1024;
export const MAX_MEMORY_IMAGES_PER_MEMORY_FREE_TIER = 20;
export const MAX_MEMORY_IMAGES_PER_UPLOAD = 20;
export const MAX_MEMORY_IMAGES_PER_DELETE = 50;
export const UNIQUE_VALUE_GENERATION_RETRIES = 10;
export const errorCodes = {
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED"
};
