/**
 * AUTH
 */
export const MIN_PASSWORD_LENGTH = 8;
export const MAX_PASSWORD_LENGTH = 20;
export const MIN_USERNAME_LENGTH = 3;
export const MAX_USERNAME_LENGTH = 20;
export const OTP_EXPIRY_TIME = "1 hour";
export const JWT_LOGIN_SESSION_DURATION = "30d";

/**
 * IMAGE SIZES
 */
export const MAX_PROFILE_IMAGE_SIZE = 5 * 1024 * 1024;
export const MAX_PASSPORT_IMAGE_SIZE = 5 * 1024 * 1024;
export const MAX_EXPENSE_RECEIPT_IMAGE_SIZE = 5 * 1024 * 1024;
export const MAX_MEMORY_IMAGE_SIZE = 20 * 1024 * 1024;

/**
 * IMAGE NUMBER
 */
export const MAX_UNIQUE_IMAGE_NAME_GENERATION_ATTEMPTS = 10;
export const MAX_MEMORY_IMAGES_PER_MEMORY_FREE_TIER = 20;
export const MAX_MEMORY_IMAGES_PER_UPLOAD = 20;
export const MAX_MEMORY_IMAGES_PER_DELETE = 50;

/**
 * CLOUDINARY PUBLIC ID PREFIXES
 */
export const PASSPORT_IMAGE_PUBLIC_ID_PREFIX = "IMG_PASS_";
export const EXPENSE_RECEIPT_PUBLIC_ID_PREFIX = "IMG_EXP_RECEIPT_";
export const PROFILE_IMAGE_PUBLIC_ID_PREFIX = "IMG_PRO_";
export const MEMORY_IMAGE_PUBLIC_ID_PREFIX = "IMG_MEM_";

/**
 * DIRECTORIES
 */
export const CLOUDINARY_PROFILE_IMAGES_FOLDER = "PROFILE_IMAGES";
export const CLOUDINARY_MEMORY_IMAGES_FOLDER = "MEMORY_IMAGES";
export const CLOUDINARY_LICENSE_DOC_FOLDER = "LICENSE_DOCS";
export const CLOUDINARY_PASSPORT_IMAGES_FOLDER = "PASSPORT_IMAGES";
export const CLOUDINARY_BUDGET_FOLDER = "BUDGETS";
export const CLOUDINARY_POST_MEDIA_FOLDER = "POSTS"

/**
 * ERROR CODES
 */
export const errorCodes = {
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED"
};

/**
 * MISCELLANEOUS
 */
export const MIN_PASSPORT_NUMBER_LENGTH = 3;
export const MIN_USER_AGE = 15;
export const MIN_LICENSE_PLATE_LENGTH = 3;
export const PROCESSING_BATCH_SIZE = 100;
export const GET_REQUEST_DATA_LIMIT = 10;
export const INTERNAL_REQUEST_ALLOWED_TIME_DIFF = 5 * 60 * 1000;
export const UNIQUE_VALUE_GENERATION_RETRIES = 10;


/**
 * COMMUNITY
 */
export const MAX_POST_CONTENT_LENGTH = 5000;
export const MAX_POST_MEDIA = 100;
export const MAX_POST_MEDIA_SIZE = 50 * 1024 * 1024 // 50 MB
export const POST_MEDIA_PUBLIC_ID_PREFIX = "MEDIA_POST_";
